name: Backend CI/CD

on:
  push:
    branches: [ "master" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "backend/**" ]
    
  workflow_dispatch:
  
jobs:
  CI-CD:
    name: Backend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
        
      - name: Install Dependencies
        run: npm install
        
      - name: Shutdown Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ./kill.sh
            sudo rm -rf backend
            exit
        
      - name: Deploy to EC2
        if: always()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "/backend"
          target: "/home/ubuntu"
          
      - name: Run Server
        if: always()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd backend
            nohup node src/app.js &
            exit
          
          
    
      
